services:
    Ast\EasyPanelBundle\Services\EasyPanelService:
        arguments: ['@twig',"%easy_panel.layoutpanel%","%easy_panel.viewpanel%","%easy_panel.viewmenu%","%easy_panel.nombreproyecto%","%easy_panel.rutalogout%"]
